### ISSUE TITLE
Merge splat 1.4.3 into refactor

### ISSUE THREAD

**Issue by der-stefan** [hoche/splat#23]
@hoche did some work before @watkipet and me started development in his unpublished 1.4.3 version. This includes:
  * antenna height changes
  * antenna azimuth and elevation reading
  * ITM instead of ITWOM used
  * DEM dynamic memory allocation
  * ...

It would be useful if we can merge those changes into the refactor branch. Changes are deep-going and must be merged carefully by hand.
@hoche: Do you plan to do the merging, as you know your changes best? Or should @watkipet and me go through it? I think it would be useful to wait for my pull request from the "json" branch, which introduces the geotiff and json output.

**Comment by hoche** [comment]
I'm somewhat busy with work right now, but I'll see if I can make some time to do it within the next week.

**Comment by watkipet** [comment]
@der-stefan --That's odd. I could have sworn that most of the items in your list were already in the refactor branch before I started. I tried to merge them in--but there's a good chance I made some mistakes. Take "ITM instead of ITOWM", for instance. I thought that was already in the refactor branch. In any case, take a look at:

Main.cpp:181,403

Isn't that making ITM the default? Maybe I missed setting the initial value of sr.olditm...

**Comment by der-stefan** [comment]
Yeah, you are right. The only issue was that sr.olditm should be initialized as false. I did that anyway in the "json" branch (which effectively is a "georeference" branch 😃).
Sorry for bothering - I kind of lost orientation. Splat is a mighty piece of software that might frighten off noobs.
Issue closed.
