### ISSUE TITLE
Encapsuling in C++ classes and cleaning folder structure

### ISSUE THREAD

**Issue by der-stefan** [hoche/splat#6]
As far as I can overview it to this point, @watkipet rewrote most of the code in a nice native C++ style with classes and objects. However, the differences with @hoche's code must be merged totally manually.

Furthermore, a standard folder structure (as of 2020) should be used (see https://github.com/kriasoft/Folder-Structure-Conventions/blob/master/README.md):

```
splat/
├── build/
├── demo/
├── docs/
├── include/
├── src/
├── utils/
├── AUTHORS
├── CHANGELOG
├── CMakeLists.txt
├── COPYING
└── README.md

**Comment by watkipet** [comment]
While working [#4](https://github.com/hoche/splat/issues/4), I'm starting to work toward this directory structure as well.

**Comment by watkipet** [comment]
Which header files should go in include?

1. Only public headers which other projects will consume?
2. All src headers only?
3. All src and util headers?

I would lean toward #1, but I'm not sure. Thoughts?

**Comment by hoche** [comment]
Public headers defining an API for other projects.

**Comment by der-stefan** [comment]
Yes, that's the point about having a library or an stand-alone program. I don't have a strong oppinion about that. Calling splat from own scripts (bash, python etc.) is alright. What would be the benefit of an splat lib? Perhaps for a potential GUI?

**Comment by dBitech** [comment]
I suppose we could view main.cc as being the front end app to the splat processing "library".  Long term I'd like to see splat be able to handle a number of modeling algorithms and able to consume arbitrary resolution terrain data, outputting any number of geo savvy raster or vector formats.

**Comment by watkipet** [comment]
I'd love to see a "libsplat" as well.

In the meantime, this is what I have in my repo for how I split things into classes:

`Anf` - Supports reading an alphanumeric output file back in (the -ani option) into an Elevation Map
`BoundaryFile` - Supports parsing a boundary file and updating an Elevation Map
`CityFile` - Supports parsing a city file and updating an Elevation Map
`Dem` - Basically just a class containing Digital Elevation Map data with all public data members for data, mask, and signal.
`ElevationMap` - This is the canvas on which all operations take place. You can plot maps, place markers, etc. on this canvas
`GnuPlot` - Supports outputting different plots from  an Elevation Map via GNU Plot
`Kml` - Represents a KML file and supports writing KML data from an Elevation Map
`Lrp` - Supports parsing and loading a .lrp file
`PatFile` - Supports parsing an antenna patterns files and exposing the data within those files
`Path` - Represents a path from one location to another. This consists of locations (lat, lon, elevation) and distances. Given two sites, the Path object can compute its data using an Elevation Map.
`Ppm` - Supports writing PPM files to disk using data from an Elevation Map
`Region` - I can’t remember about this one. I need to look into it more.
`Report` - Can generate different textual reports from Sites and an Elevation Map
`Sdf` - Supports loading SDF files into an Elevation Map
`Site` - Represents either a transmitting or receiving site
`SplatRun` - The parameters for an invocation of Splat! such as ippd, the RX site, whether KML files should be produced, etc.
`Udt` - Supports reading User-Defined Terrain files into an Elevation Map.
`Utilities` - General purpose utilities for file paths, etc.

My goal is to keep as much as I can out of the Elevation Map itself. That class should be the "canvas" where splat does all its computing and it should be agnostic of the input and output formats. That's why you see the other objects accessing information in the Elevation Map and submitting data into the Elevation Map.

**Comment by watkipet** [comment]
@hoche and @der-stefan - Do my classes above look OK as a starting point? There's a lot more future work I'd like to do in this respect, but in my repo, I was able to split into those classes while leaving the code in the functions mostly the same. I'll try and merge the improvements you made, @hoche, into the appropriate classes.

These would by no means be the final classes, but they might give us a starting point to work from.

However, if you'd like to come up with an entirely different class scheme, I'm fine with that too.

**Comment by hoche** [comment]
I'll probably write up more on this at some point, but my general thinking is that SPLAT is an engine that does three things: consume input files (terrain, site data, antenna rad patterns), feeds that to a propagation model (currently itm, iwom, or LoS), and then generates output files.

The input side of things can be driven from a GUI, a commandline with switches, a webinterface with CGI parameters or a JSON interface or something, or a series of function calls from a scripting language.

The propagation models should be able to be plugged in as needed.

The output side of things should be pretty flexible and allow for different sort of outputs, probably also handled as plugins.

Back to the question at hand: yes, I think these classes are a really good starting point. Obviously some things are going to change - ppms would now be a more generic image object, for example. But in general I think we can go ahead with your division.

I'm in the middle of moving the Dems and Paths to individual classes at the moment.

**Comment by der-stefan** [comment]
@watkipet: Your proposed classes look reasonable. They will make it easier to get and set their object's properties. 👍

**Comment by dBitech** [comment]
I concur, the existing proposed classes are a good starting point to move to wars the end goal.

**Comment by watkipet** [comment]
Yes, I agree with eventually getting to an architecture where inputs, outputs, models, are abstracted and more can be added without major changes to the core. That would be wonderful.

OK. I put all my classes in on [iss6](https://github.com/hoche/splat/tree/iss6). However, all I've done so far is add them and change the CMakeLists.txt to use them instead. So that means none of @hoche's improvements are merged in yet. Also, there are some coding standard violations (using namespace std), some inconsistent Doxygen style comments (some use /**, others ///).

My first task is going to be using #hoche's improved and commented `itwom3.0.c` instead of the original, which I had named `itwom3.0.cpp`.

**Comment by watkipet** [comment]
The new itowom3.0 is in [iss6](https://github.com/hoche/splat/tree/iss6) now. I also merged in @hoche's MT code for ElevationMap::PlotLOSMap. The command-line arguments are still missing for MT, though. I'll merge in more MT code later.

**Comment by der-stefan** [comment]
Very good work! Just a question: Why do you create new branches for every issue? When do you delete them after merging?

**Comment by watkipet** [comment]
I create the branches to associate my changes with a specific issue. Git doesn't have Change Packages like some other SCM systems, so I use branches. I think this is common practice. I'm using the naming convention [shown here](https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging). We can delete them any time now.

Hopefully this practice also allows for more concurrent work. I might temporarily break something in my branch (multithreading for instance). Someone else may be finishing up their issue and they may need my Site class, but they don't want my ElevationMap class because multithreading is broken. They can just merge the files they want into their branch, finish up their issue, and then merge their branch back into `refactor`. Then when I go to merge my branch, I'll see that some of my files are already in `refactor`--which makes my job easier. I think this actually happened with some of the CMakeList.txt files for #4. It made my job easier when I merged my branch back in.

However, I'm only looking at this from my perspective. Did it make it more difficult for others when I made my changes on separate branches?

**Comment by watkipet** [comment]
PlotLRMap is merged now too. However, the results aren't going to be valid because I'm not allocating a new Path object in each invocation of PlotLRPath so each thread is going to clobber the shared Path object used by all the other threads. I just need to merge Plot LRPath to fix this. Will do that later.

**Comment by der-stefan** [comment]
@watkipet: Thank you very much for the detailled explanation - it is absolutely reasonable.  I don't have the experience with greater collaborative git projects yet and speculated about the International Space Station at first... 🙈 Great to have you here!

Back to the issue: I would like to contribute new functionallity (json and geotiff outputs), but will wait for the finished classes. I need to adopt and learn the coding style, since I'm not yet experienced in clean programming ("just make it work" 😕) and don't want to mess up the project again.

**Comment by watkipet** [comment]
@hoche and @der-stefan - Sorry it's taken me so long to make more progress. Life has been a little different lately. I hope you all are staying healthy. I renamed my Ppm class to Image. It now uses ImageWriter.

@hoche, one thing I'm confused about is the `cityorcounty` variable--it's removed in your WriteImage* routines. Should I remove it too?

**Comment by hoche** [comment]
@Peter, I'm doing fine and hope you have been well too. I've been 
wrapped up in other projects but hope to get back to this in the next 
week or so.

Anyway, I had to scratch my head for a bit trying to remember why I 
removed cityorcounty, but it turns out it was unnecessary. It's 
essentially the following logic:

cityorcounty = 0; if (mask&2) {     ...     cityorcounty = 1; } else if 
(mask&4) {     ...     cityorcounty = 1; } if (cityorcounty == 0) {     
... }

I.e. the last block only gets hit if both the mask tests are false. That 
means you can flip it around like so:

if (mask&2) {
     ...
} else if (mask&4) {
     ...
} else {
     ...
}

and just get rid of the flag variable.

**Comment by watkipet** [comment]
I think I'm ready to merge this into the mainline and close the issue. I'm sure there will be some bugs, but I did some very rudimentary testing. It doesn't crash and burn at least. Here's some output from the sample data. I ran this command:

`splat -t ~/src/github/hoche/splat/sample_data/wnju-dt.qth -sdelim _ -L 5 -maxpages 4 -jpg`

![wnju-dt](https://user-images.githubusercontent.com/969829/80770896-83788600-8b06-11ea-8cba-27fb163f7f16.jpg)

[WNJU-DT-site_report.txt](https://github.com/hoche/splat/files/4561978/WNJU-DT-site_report.txt)

**Comment by dBitech** [comment]
I tossed a half dozen locations at it and seems to work as advertised.

**Comment by hoche** [comment]
Wow. Looks good, man. Like really good. Kudos for all your hard work.

I did find a few bugs but if you want to push it to the "refactor" branch go ahead and they can be fixed there. I want to rework some more things before it gets to being a release candidate anyway.

**Comment by watkipet** [comment]
@dBitech - Thanks for testing! @hoche - Thanks for the kind words and fixes. I merged the branch (iss6) and deleted it.
